/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox1;
  GtkWidget *vbox4;
  GtkWidget *vbox2;
  GtkWidget *lbl_pattern;
  GtkWidget *scrolledwindow1;
  GtkWidget *tv_pattern;
  GtkWidget *hbox1;
  GtkWidget *lbl_pattern_status;
  GtkWidget *alignment1;
  GtkWidget *hbox2;
  GtkWidget *chk_mod_i;
  GtkWidget *chk_mod_m;
  GtkWidget *chk_mod_s;
  GtkWidget *chk_mod_x;
  GtkWidget *chk_mod_g;
  GtkWidget *vbox3;
  GtkWidget *lbl_subject;
  GtkWidget *scrolledwindow2;
  GtkWidget *tv_subject;
  GtkWidget *lbl_subject_status;
  GtkWidget *hbuttonbox1;
  GtkWidget *btn_test_pattern;
  GtkWidget *btn_generate_graphic;
  GtkWidget *btn_close;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main_window, "main_window");
  gtk_widget_set_size_request (main_window, 400, 450);
  gtk_container_set_border_width (GTK_CONTAINER (main_window), 3);
  gtk_window_set_title (GTK_WINDOW (main_window), _("Rexpert"));
  gtk_window_set_default_size (GTK_WINDOW (main_window), 400, 450);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox4, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox2, TRUE, TRUE, 0);

  lbl_pattern = gtk_label_new (_("Pattern:"));
  gtk_widget_set_name (lbl_pattern, "lbl_pattern");
  gtk_widget_show (lbl_pattern);
  gtk_box_pack_start (GTK_BOX (vbox2), lbl_pattern, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (lbl_pattern), 0, 0.5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  tv_pattern = gtk_text_view_new ();
  gtk_widget_set_name (tv_pattern, "tv_pattern");
  gtk_widget_show (tv_pattern);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), tv_pattern);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, FALSE, TRUE, 0);

  lbl_pattern_status = gtk_label_new (_("Insert a pcre-compatible pattern"));
  gtk_widget_set_name (lbl_pattern_status, "lbl_pattern_status");
  gtk_widget_show (lbl_pattern_status);
  gtk_box_pack_start (GTK_BOX (hbox1), lbl_pattern_status, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (lbl_pattern_status), 0, 0.5);

  alignment1 = gtk_alignment_new (1, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (hbox1), alignment1, FALSE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox2);

  chk_mod_i = gtk_check_button_new_with_mnemonic (_("i"));
  gtk_widget_set_name (chk_mod_i, "chk_mod_i");
  gtk_widget_show (chk_mod_i);
  gtk_box_pack_start (GTK_BOX (hbox2), chk_mod_i, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, chk_mod_i, _("Caseless pattern matching"), NULL);

  chk_mod_m = gtk_check_button_new_with_mnemonic (_("m"));
  gtk_widget_set_name (chk_mod_m, "chk_mod_m");
  gtk_widget_show (chk_mod_m);
  gtk_box_pack_start (GTK_BOX (hbox2), chk_mod_m, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, chk_mod_m, _("Multiline pattern matching"), NULL);

  chk_mod_s = gtk_check_button_new_with_mnemonic (_("s"));
  gtk_widget_set_name (chk_mod_s, "chk_mod_s");
  gtk_widget_show (chk_mod_s);
  gtk_box_pack_start (GTK_BOX (hbox2), chk_mod_s, TRUE, TRUE, 0);

  chk_mod_x = gtk_check_button_new_with_mnemonic (_("x"));
  gtk_widget_set_name (chk_mod_x, "chk_mod_x");
  gtk_widget_show (chk_mod_x);
  gtk_box_pack_start (GTK_BOX (hbox2), chk_mod_x, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, chk_mod_x, _("Extended pattern matching"), NULL);

  chk_mod_g = gtk_check_button_new_with_mnemonic (_("g"));
  gtk_widget_set_name (chk_mod_g, "chk_mod_g");
  gtk_widget_show (chk_mod_g);
  gtk_box_pack_start (GTK_BOX (hbox2), chk_mod_g, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox3, TRUE, TRUE, 0);

  lbl_subject = gtk_label_new (_("Subject text:"));
  gtk_widget_set_name (lbl_subject, "lbl_subject");
  gtk_widget_show (lbl_subject);
  gtk_box_pack_start (GTK_BOX (vbox3), lbl_subject, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (lbl_subject), 0, 0.5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  tv_subject = gtk_text_view_new ();
  gtk_widget_set_name (tv_subject, "tv_subject");
  gtk_widget_show (tv_subject);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), tv_subject);

  lbl_subject_status = gtk_label_new (_("Insert a text to be tested against the pattern"));
  gtk_widget_set_name (lbl_subject_status, "lbl_subject_status");
  gtk_widget_show (lbl_subject_status);
  gtk_box_pack_start (GTK_BOX (vbox3), lbl_subject_status, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (lbl_subject_status), 0, 0.5);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  btn_test_pattern = gtk_button_new_with_mnemonic (_("Test pattern"));
  gtk_widget_set_name (btn_test_pattern, "btn_test_pattern");
  gtk_widget_show (btn_test_pattern);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), btn_test_pattern);
  GTK_WIDGET_SET_FLAGS (btn_test_pattern, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, btn_test_pattern, _("Click here to test the pattern"), NULL);
  gtk_widget_add_accelerator (btn_test_pattern, "clicked", accel_group,
                              GDK_Return, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  btn_generate_graphic = gtk_button_new_with_mnemonic (_("Generate graphic"));
  gtk_widget_set_name (btn_generate_graphic, "btn_generate_graphic");
  gtk_widget_show (btn_generate_graphic);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), btn_generate_graphic);
  gtk_widget_set_sensitive (btn_generate_graphic, FALSE);
  GTK_WIDGET_SET_FLAGS (btn_generate_graphic, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, btn_generate_graphic, _("Click here to generate a graphviz graphic of the results"), NULL);

  btn_close = gtk_button_new_with_mnemonic (_("Close"));
  gtk_widget_set_name (btn_close, "btn_close");
  gtk_widget_show (btn_close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), btn_close);
  GTK_WIDGET_SET_FLAGS (btn_close, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, btn_close, _("Click to close the application"), NULL);

  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) btn_test_pattern, "clicked",
                    G_CALLBACK (on_btn_test_pattern_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_close, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (main_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main_window, lbl_pattern, "lbl_pattern");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (main_window, tv_pattern, "tv_pattern");
  GLADE_HOOKUP_OBJECT (main_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main_window, lbl_pattern_status, "lbl_pattern_status");
  GLADE_HOOKUP_OBJECT (main_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (main_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (main_window, chk_mod_i, "chk_mod_i");
  GLADE_HOOKUP_OBJECT (main_window, chk_mod_m, "chk_mod_m");
  GLADE_HOOKUP_OBJECT (main_window, chk_mod_s, "chk_mod_s");
  GLADE_HOOKUP_OBJECT (main_window, chk_mod_x, "chk_mod_x");
  GLADE_HOOKUP_OBJECT (main_window, chk_mod_g, "chk_mod_g");
  GLADE_HOOKUP_OBJECT (main_window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (main_window, lbl_subject, "lbl_subject");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (main_window, tv_subject, "tv_subject");
  GLADE_HOOKUP_OBJECT (main_window, lbl_subject_status, "lbl_subject_status");
  GLADE_HOOKUP_OBJECT (main_window, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (main_window, btn_test_pattern, "btn_test_pattern");
  GLADE_HOOKUP_OBJECT (main_window, btn_generate_graphic, "btn_generate_graphic");
  GLADE_HOOKUP_OBJECT (main_window, btn_close, "btn_close");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

  gtk_widget_grab_focus (tv_pattern);
  gtk_widget_grab_default (btn_test_pattern);
  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

